services:
  # 1. 메인 API 서버 (FastAPI)
  backend:
    build: ./backend
    restart: on-failure
    container_name: dot_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./ai_models:/ai_models
    depends_on:
      - db
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      # MySQL 컨테이너 이름인 'db'를 호스트로 사용해야 합니다.
      - DATABASE_URL=mysql+pymysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}
      - REDIS_URL=redis://redis:6379/${REDIS_DB}
      - PYTHONPATH=/app
    networks:
      - dot_network

  # 2. AI 작업 워커 (Celery)
  worker:
    build: ./backend
    container_name: dot_worker
    command: celery -A worker.celery_app worker --loglevel=info
    #command: tail -f /dev/null
    volumes:
      - ./backend:/app
      - ./ai_models:/ai_models
    depends_on:
      - redis
      - backend
    environment:
      # backend와 동일한 DB 접속 정보 사용
      - DATABASE_URL=mysql+pymysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}
      - REDIS_URL=redis://redis:6379/${REDIS_DB}
      - PYTHONPATH=/app
    networks:
      - dot_network

  # 3. 데이터베이스 (MySQL 8.0)
  db:
    image: mysql:8.0
    container_name: dot_db
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${WORKER_DB_USER}"
      MYSQL_PASSWORD: "${WORKER_DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dot_network

  # 4. 메시지 브로커 (Redis)
  redis:
    image: redis:alpine
    container_name: dot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dot_network

  # 5. 프론트엔드 (Vite)
  frontend:
    build: ./frontend
    container_name: dot_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - dot_network

volumes:
  db_data:
  redis_data:

networks:
  dot_network:
    driver: bridge